project_improvement/config/routes.rb
ProjectImprovement::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :passwords => "users/passwords"}

  devise_scope :user do
    get '/users/auth/:provider/callback' => "users/omniauth_callbacks#connect"
  end

  post "/users/auth/:provider/callback" => "users/sessions#create"

  resources :dashboard

  resources :home

  patch "/user" => "dashboard#update", as: :user

  root 'home#index'

end

project_improvement/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	layout 'layouts/application'
	before_filter :authenticate_user!, :except => [:index]

	def index
	  @user = User.find current_user.id
	end

	def edit
	  @user = User.find current_user.id
	end

	def update
	  @user = User.find current_user.id
	  @status = false
	  	if @user.update_attributes(user_params)
	  	  @status = true
	  	else
	  	  @error_messages = @user.errors.full_messages
	  	end
	  respond_to do |format|
	  	format.js
	  end
	end

	private

	def user_params
	  params.require(:user).permit(:id, :avatar, :first_name, :last_name, :email, :password, :password_confirmation)
	end
end

project_improvement/app/helpers/dashboard_helper.rb
module DashboardHelper
end

project_improvement/app/views/dashboard/_ajax.html.erb
<%= content_for :bottom_scripts do %>
  <script type="text/javascript">
    $(".submit_button").click(function(){
      $.ajax({
      	type: "put",
      	url: "<%= dashboard_path %>",
      	dataType: "json",
      	data: {id: $('#user_id').val(), first_name: $('#user_first_name').val(), last_name: $('#user_last_name').val(), email: $('#user_email').val(), password: $('#user_password').val(), password_confirmation: $('#user_password_confirmation').val(), avatar: $('#user_avatar').val()},
      	success:function(response){
      	  if (response){
      	  	alert("User successfully updated");
      	  	window.location.replace("<%= dashboard_index_path %>");
      	  }else{
            $(".validation").show();
      	  }
      	}
      })
    });
  </script>
<%end%>

project_improvement/app/views/dashboard/_index_js.html.erb
<%= content_for :bottom_scripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
    <% if params[:sucess] == "true" %>
      alert('aaa');
    <%end%>
    });
  </script>
<%end%>

project_improvement/app/views/dashboard/edit.html.erb
<h2>Update Profile</h2>

<%= form_for(@user, :html => {:multipart => true, :remote => true}) do |f| %>
<div class="validation"></div>
	<div>
		<%= f.label :first_name %><br/>
		<%= f.text_field :first_name %>
	</div>
	<div>
		<%= f.label :last_name %><br/>
		<%= f.text_field :last_name %>
	</div>
	<div>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div>
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :confirmation %>
	</div>
	<div>
		<%= f.label :avatar %><br/>
		<%= f.file_field :avatar %>
		<br/>
		<% unless @user.avatar.nil? %>
		  <%= image_tag @user.avatar.url(:thumb) %>
		<%end%>
	</div>
	<br/>
	<%= f.hidden_field :id %>
	<div><%= f.submit "Update" %></div>
<%end%>

<%= render "ajax" %>

project_improvement/app/views/dashboard/index.html.erb
	<div>
		<%= label_tag "First Name" %><br/>
		<%= @user.first_name %>
	</div>
	<div>
		<%= label_tag "Last Name" %><br/>
		<%= @user.last_name %>
	</div>
	<div>
		<%= label_tag "Email" %><br/>
		<%= @user.email %>
	</div>
	<div>
		<%= label_tag "Avatar" %><br/>
		<br/>
		<% unless @user.avatar.nil? %>
		  <%= image_tag @user.avatar.url(:thumb) %>
		<%end%>
	</div>
	<%= link_to "Update", edit_dashboard_path(current_user.id) %>

<%= render "index_js" %>

project_improvement/app/views/dashboard/update.js.erb
<% if @status %>
  alert("User profile successfully updated");
  window.location = "<%= dashboard_index_path %>";
<% else %>
  $(".validation").html("");
  <% @error_messages.each do |message| %>
    $(".validation").append("<p><%= message %></p>")
  <% end %>
<% end %>